'''
    gameStates.py :
        here the available game states are defined
'''

gameStates={
    'still': {
        'name': 'still',
        'integrate': False,
        'displaywf': False,
        'keysToSend': {'g','i','1','2','c','v','b','m'},
        'sleep': 0.05,
        'moveCursors': False,
        'limitFrameRate': False,
        'musicMode': 'menu',
    },
    'info': {
        'name': 'info',
        'integrate': False,
        'displaywf': False,
        'keysToSend': {'i'},
        'sleep': 0.05,
        'moveCursors': False,
        'limitFrameRate': False,
        'musicMode': 'menu',
    },
    'play': {
        'name': 'play',
        'integrate': True,
        'displaywf': True,
        'keysToSend': {'i', ' ','b'},
        'sleep': 0.0,
        'moveCursors': True,
        'limitFrameRate': True,
        'musicMode': 'game',
    },
    'paused': {
        'name': 'paused',
        'integrate': False,
        'displaywf': True,
        'keysToSend': {'i', ' ','b'},
        'sleep': 0.05,
        'moveCursors': False,
        'limitFrameRate': False,
        'musicMode': 'game',
    },
    'showendmatch': {
        'name': 'showendmatch',
        'integrate': False,
        'displaywf': True,
        'keysToSend': {'i'},
        'sleep': 0.05,
        'moveCursors': False,
        'limitFrameRate': False,
        'musicMode': 'game',
    },
    'showendplay': {
        'name': 'showendplay',
        'integrate': False,
        'displaywf': True,
        'keysToSend': {},
        'sleep': 0.05,
        'moveCursors': False,
        'limitFrameRate': False,
        'musicMode': None,
    },
    'quitting': {
        'name': 'quitting',
        'integrate': False,
        'displaywf': False,
        'keysToSend': {'y','n'},
        'sleep': 0.05,
        'moveCursors': False,
        'limitFrameRate': False,
        'musicMode': 'menu',
    },
    'prestarting': {
        'name': 'prestarting',
        'integrate': False,
        'displaywf': False,
        'keysToSend': {},
        'sleep': 0.01,
        'moveCursors': False,
        'limitFrameRate': False,
        'musicMode': None,
    },
    'initplay': {
        'name': 'initplay',
        'integrate': False,
        'displaywf': False,
        'keysToSend': {},
        'sleep': 0.01,
        'moveCursors': False,
        'limitFrameRate': False,
        'musicMode': 'game',
    },
    'starting': {
        'name': 'starting',
        'integrate': False,
        'displaywf': True,
        'keysToSend': {},
        'sleep': 0.005,
        'moveCursors': False,
        'limitFrameRate': False,
        'musicMode': 'game',
    },
}
